# Sử dụng Node.js image làm base
FROM node:16

# Đặt thư mục làm việc trong container
WORKDIR /app

# Sao chép package.json và package-lock.json vào container
COPY package.json package-lock.json ./

# Cài đặt các phụ thuộc
RUN npm install --legacy-peer-deps

# Cài đặt Vite
RUN npm install vite --save-dev

# Sao chép toàn bộ mã nguồn vào container
COPY . .

# Mở port mà Vite sẽ chạy
EXPOSE 3001

# Chạy lệnh để start Vite (client)
CMD ["npm", "run", "dev"]
