version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      target: development
    ports:
      - "5173:5173"   # Ánh xạ cổng từ container ra máy chủ vật lý
    stdin_open: true
    volumes:
      - ./frontend:/usr/src/app  # Ánh xạ thư mục frontend từ máy chủ vật lý vào container
      - /usr/src/app/node_modules  # Giữ lại node_modules trong container
    restart: always
    networks:
      - react-express-chat
    depends_on:
      - backend  # Đảm bảo backend đã sẵn sàng trước khi frontend khởi động

backend:
  restart: always
  build:
    context: ./backend
    target: development
  volumes:
    - ./backend:/usr/src/app
    - /usr/src/app/node_modules
  networks:
    - react-express-chat
  expose:
    - "3001"  # Expose cổng trong container cho các dịch vụ khác trong mạng Docker
  ports:
    - "3001:3001"  # Ánh xạ cổng 3001 từ container ra máy chủ vật lý


networks:
  react-express-chat:
    driver: bridge  # Sử dụng mạng bridge để frontend và backend có thể giao tiếp
