version: '3.8'

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "3001:3001" # Vite client sẽ chạy trên port 3000
    volumes:
      - .:/app
    depends_on:
      - server

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "5000:5000" # WebSocket server sẽ chạy trên port 5000
    volumes:
      - .:/app
