services:
  frontend:
    build:
      context: frontend
      target: development
    ports:
      - 5173:5173
    stdin_open: true
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
    networks:
      - react-express-chat
    depends_on:
      - backend

  backend:
    restart: always
    build:
      context: backend
      target: development
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - react-express-chat
    expose:
      - 3001
    ports:
    - "3001:3001"

networks:
  react-express-chat:
